image: python:latest

stages:
 - test

services:
  - docker:dind
  
bandit:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install bandit
    - 'bandit -r app.py  > bandit-output.txt '
  artifacts:
    paths: [bandit-output.txt]
  

devskim:
    image: docker:latest
    stage: test
    
    script:
      - docker run --volume `pwd`:/code coderpatros/devskim:latest analyze /code
      - python3 -m pytest --junitxml=tests.xml app.py
    artifacts:
      paths: [tests.xml]

trufflehog:
   image: docker:latest
   stage: test

   script:
    - docker run --rm -v "$(pwd):/proj" dxa4481/trufflehog file:///proj

taint:
   image: docker:latest
   stage: test

   script:
    - docker run --rm --volume \$(pwd) vickyrajagopal/python-taint-docker pyt .

owasp:
   image: docker:latest
   stage: test

   script:
     - echo 'hello!'
     - docker run -t owasp/zap2docker-stable zap-baseline.py -t http://56d6c3d7cfd6.ngrok.io
   allow_failure: true
